---
title: "Computing Zscore"
author: "IBRAHIM KASSOUM Habibou"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
#  officedown::rdocx_document:
#    mapstyles:
#      Normal: ['First Paragraph']

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, error=FALSE)
rm(list=ls())
```



## Importing library

```{r Package needed, results = "hide", include = FALSE, warning=FALSE, echo = TRUE}


## Importing library
### List of required packages
required_packages <- c("devtools")

# Check if packages are installed
missing_packages <- setdiff(required_packages, installed.packages()[,"Package"])

### Install missing packages
if (length(missing_packages) > 0) {
  install.packages(missing_packages)
}

### Load all packages
lapply(required_packages, library, character.only = TRUE)


# if not already installed
#install.packages('devtools', repos = 'http://cran.us.r-project.org') 

# note: "V" is capitalized
devtools::install_github("hemken/Statamarkdown")
```

```{r, echo=FALSE, message=FALSE}
## This package is designed to compute stata codes in R.
## here is the links to more informations: https://rpubs.com/quarcs-lab/stata-from-Rstudio
library(Statamarkdown)
```


```{stata, echo=FALSE, cleanlog=FALSE, message=FALSE}


## Set working directory
cd "C:\Users\ASUS\Dropbox\PhD thesis\chapitre_2\Unequal-Plate"
capture mkdir ".\input\zanthro"
cd ".\input\zanthro"
net get dm0004_1, from(http://www.stata-journal.com/software/sj13-2/)

########################################################################################################################################################
########################################## df global ###################################################################################################
########################################################################################################################################################

### Importing the file 'df_global'
import excel "C:\Users\ASUS\Dropbox\PhD thesis\chapitre_2\Unequal-Plate\output\data\df_global.xlsx", sheet("Sheet1") firstrow clear

### Created the zscore for the df_global
egen waz_who = zanthro(weight_kg,wa,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)
egen haz_who = zanthro(height_cm,ha,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)
egen bmiz_who = zanthro(bmi,ba,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)

### Exporting results
export excel using "C:\Users\ASUS\Dropbox\PhD thesis\chapitre_2\Unequal-Plate\output\data\df_global.xlsx", firstrow(variables) replace


########################################################################################################################################################
########################################## df_global_corrected ###################################################################################################
########################################################################################################################################################

### Importing the file 'df_global_corrected'
import excel "C:\Users\ASUS\Dropbox\PhD thesis\chapitre_2\Unequal-Plate\output\data\df_global_corrected.xlsx", sheet("Sheet1") firstrow clear

### Created the zscore for the df_global
egen waz_who = zanthro(weight_kg,wa,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)
egen haz_who = zanthro(height_cm,ha,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)
egen bmiz_who = zanthro(bmi,ba,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)

### Exporting results
export excel using "C:\Users\ASUS\Dropbox\PhD thesis\chapitre_2\Unequal-Plate\output\data\df_global_corrected.xlsx", firstrow(variables) replace


########################################################################################################################################################
########################################## Round 1 data ################################################################################################
########################################################################################################################################################
## For underfive household member
### Importing the file 'r1' data
import excel "C:\Users\ASUS\Dropbox\PhD thesis\chapitre_2\Unequal-Plate\output\data\r1_underfive.xlsx", sheet("Sheet1") firstrow clear

### Created the zscore for the df_global
egen waz_who = zanthro(weight_kg,wa,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)
egen haz_who = zanthro(height_cm,ha,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)
egen bmiz_who = zanthro(bmi,ba,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)

### Exporting results
export excel using "C:\Users\ASUS\Dropbox\PhD thesis\chapitre_2\Unequal-Plate\output\data\r1_underfive.xlsx", firstrow(variables) replace

## For overfive household member
### Importing the file 'r1' data
import excel "C:\Users\ASUS\Dropbox\PhD thesis\chapitre_2\Unequal-Plate\output\data\r1_overfive.xlsx", sheet("Sheet1") firstrow clear

### Created the zscore for the df_global
egen waz_who = zanthro(weight_kg,wa,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)
egen haz_who = zanthro(height_cm,ha,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)
egen bmiz_who = zanthro(bmi,ba,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)

### Exporting results
export excel using "C:\Users\ASUS\Dropbox\PhD thesis\chapitre_2\Unequal-Plate\output\data\r1_overfive.xlsx", firstrow(variables) replace


########################################################################################################################################################
########################################## Round 2 data ################################################################################################
########################################################################################################################################################
## For underfive household member
### Importing the file 'r2' data
import excel "C:\Users\ASUS\Dropbox\PhD thesis\chapitre_2\Unequal-Plate\output\data\r2_underfive.xlsx", sheet("Sheet1") firstrow clear

### Created the zscore for the df_global
egen waz_who = zanthro(weight_kg,wa,WHO), xvar(age_month) gender(hhm_sex) gencode(m=male, f=female) ageunit(month)
egen haz_who = zanthro(height_cm,ha,WHO), xvar(age_month) gender(hhm_sex) gencode(m=male, f=female) ageunit(month)
egen bmiz_who = zanthro(bmi,ba,WHO), xvar(age_month) gender(hhm_sex) gencode(m=male, f=female) ageunit(month)

### Exporting results
export excel using "C:\Users\ASUS\Dropbox\PhD thesis\chapitre_2\Unequal-Plate\output\data\r2_underfive.xlsx", firstrow(variables) replace

## For overfive household member
### Importing the file 'r1' data
import excel "C:\Users\ASUS\Dropbox\PhD thesis\chapitre_2\Unequal-Plate\output\data\r2_overfive.xlsx", sheet("Sheet1") firstrow clear

### Created the zscore for the df_global
egen waz_who = zanthro(weight_kg,wa,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)
egen haz_who = zanthro(height_cm,ha,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)
egen bmiz_who = zanthro(bmi,ba,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)

### Exporting results
export excel using "C:\Users\ASUS\Dropbox\PhD thesis\chapitre_2\Unequal-Plate\output\data\r2_overfive.xlsx", firstrow(variables) replace



########################################################################################################################################################
########################################## Round 3 data ################################################################################################
########################################################################################################################################################
## For underfive household member
### Importing the file 'r1' data
import excel "C:\Users\ASUS\Dropbox\PhD thesis\chapitre_2\Unequal-Plate\output\data\r3_underfive.xlsx", sheet("Sheet1") firstrow clear

### Created the zscore for the df_global
egen waz_who = zanthro(weight_kg,wa,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)
egen haz_who = zanthro(height_cm,ha,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)
egen bmiz_who = zanthro(bmi,ba,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)

### Exporting results
export excel using "C:\Users\ASUS\Dropbox\PhD thesis\chapitre_2\Unequal-Plate\output\data\r3_underfive.xlsx", firstrow(variables) replace

## For overfive household member
### Importing the file 'r1' data
import excel "C:\Users\ASUS\Dropbox\PhD thesis\chapitre_2\Unequal-Plate\output\data\r3_overfive.xlsx", sheet("Sheet1") firstrow clear

### Created the zscore for the df_global
egen waz_who = zanthro(weight_kg,wa,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)
egen haz_who = zanthro(height_cm,ha,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)
egen bmiz_who = zanthro(bmi,ba,WHO), xvar(hhm_age) gender(hhm_sex) gencode(m=male, f=female) ageunit(year)

### Exporting results
export excel using "C:\Users\ASUS\Dropbox\PhD thesis\chapitre_2\Unequal-Plate\output\data\r3_overfive.xlsx", firstrow(variables) replace




```

